// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rnbernexp_CPP
SEXP rnbernexp_CPP(SEXP g, SEXP ep, SEXP oh, SEXP th);
RcppExport SEXP _individual_network_rnbernexp_CPP(SEXP gSEXP, SEXP epSEXP, SEXP ohSEXP, SEXP thSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type g(gSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ep(epSEXP);
    Rcpp::traits::input_parameter< SEXP >::type oh(ohSEXP);
    Rcpp::traits::input_parameter< SEXP >::type th(thSEXP);
    rcpp_result_gen = Rcpp::wrap(rnbernexp_CPP(g, ep, oh, th));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_individual_network_rnbernexp_CPP", (DL_FUNC) &_individual_network_rnbernexp_CPP, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_individual_network(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
