# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rnbernexp_CPP <- function(g, ep, oh, th) {
    .Call('_individual_network_rnbernexp_CPP', PACKAGE = 'individual.network', g, ep, oh, th)
}

